CREATE DATABASE clinica_unisagrado;

CREATE TABLE clinica_unisagrado.patients (
    id int NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name varchar(255),
    dt_birthday DATETIME,
    gender ENUM('F', 'M'),
    weight DOUBLE(40,2),
    height DOUBLE(40,2),
    race ENUM('BRANCA', 'NEGRA', 'PARDA'),
    schooling varchar(255),
    profession varchar(255),
    rg varchar(255),
    CPF varchar(11) UNIQUE,
    marital_status varchar(255),
    nationality varchar(255),
    birth_state varchar(255),
    father_name varchar(255),
    father_nationality varchar(255),
    mother_name varchar(255),
    mother_nationality varchar(255),
    telephone varchar(255),
    cellphone varchar(255),
    address varchar(255),
    address_number varchar(255),
    complement varchar(255),
    district varchar(255),
    CEP varchar(255),
    city varchar(255),
    state varchar(255),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE clinica_unisagrado.ficha_avaliacao (
    id int NOT NULL PRIMARY KEY AUTO_INCREMENT,
    queixa text,
    doenca_atual text,
    hemorragia ENUM('S', 'N'),
    alergia ENUM('S', 'N'),
    reumatismo ENUM('S', 'N'),
    cardiovascular ENUM('S', 'N'),
    gastrite ENUM('S', 'N'),
    diabetico ENUM('S', 'N'),
    desmaiou ENUM('S', 'N'),
    tratamentos ENUM('S', 'N'),
    medicamentos ENUM('S', 'N'),
    doencas_ou_cirurgias ENUM('S', 'N'),
    vicios ENUM('S', 'N'),
    ansiedade ENUM('S', 'N'),
    tuberculose ENUM('S', 'N'),
    sifilis ENUM('S', 'N'),
    hepatite ENUM('S', 'N'),
    sida_aids ENUM('S', 'N'),
    sarampo ENUM('S', 'N'),
    caxumba ENUM('S', 'N'),
    varicela ENUM('S', 'N'),
    outras_doencas varchar(255),
    fumante ENUM('S', 'N'),
    frequencia varchar(100),
    gestacao text,
    parto ENUM('N', 'F', 'C'),
    parto_problemas ENUM('S', 'N'),
    amamentacao ENUM('N', 'M'),
    amamentacao_idade int,
    anestesia ENUM('S', 'N'),
    graves_contagiosas ENUM('S', 'N'),
    vacina ENUM('S', 'N'),
    labios ENUM('N', 'A'),
    mucosa_jugal ENUM('N', 'A'),
    lingua ENUM('N', 'A'),
    soalho_boca ENUM('N', 'A'),
    garganta ENUM('N', 'A'),
    palato_mole ENUM('N', 'A'),
    mucosa_alveolar ENUM('N', 'A'),
    gengivas ENUM('N', 'A'),
    glandulas_salivares ENUM('N', 'A'),
    linfonodos ENUM('N', 'A'),
    atm ENUM('N', 'A'),
    musculos_mastigadores ENUM('N', 'A'),
    palato_duro ENUM('N', 'A'),
    oclusao ENUM('N', 'A'),
    alteracoes text,
    pressao_maxima varchar(10),
    pressao_minima varchar(10),
    diagnostico_presuntivo text,
    exames_complementares text,
    diagnostico_definitivo text,
    tratamento_proservacao text,
    plano_tratamento text,
    patient_id int NOT NULL,
    CONSTRAINT FK_PatientFichaAvalicao FOREIGN KEY (patient_id)
    REFERENCES patients(id)
);