version: "3"

services:
  php:
    container_name: "php-srv"
    image: php:7.4-fpm
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    ports:
      - "9000:9000"
    restart: unless-stopped
    links:
      - mysql
    networks:
      - mynetwork
    depends_on:
      - mysql

  nginx:
    container_name: "nginx-srv"
    image: nginx:1.19
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    networks:
      - mynetwork
    depends_on:
      - php

  mysql:
    container_name: "mysql-srv"
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: root
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    restart: unless-stopped
    ports:
      - "3306:3306"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
